
DEFAULT_PROMPT = "Введите начальный текст для генерации:"
DEFAULT_MAX_LENGTH = 150
DEFAULT_REPETITION_PENALTY = 5.0
DEFAULT_TOP_K = 5
DEFAULT_TOP_P = 0.95
DEFAULT_TEMPERATURE = 1.0
DEFAULT_NUM_BEAMS = 10
DEFAULT_NO_REPEAT_NGRAM_SIZE = 3
